@startuml
interface ActionComponent {
    +execute(Receipt receipt)
}

class ActionComposite {
    -name: String
    -actions: List<ActionComponent>
    +addAction(ActionComponent action)
    +execute(Receipt receipt)
    +getName()
}

class ActionConstants{
    +MAKE_COFFEE: String
    +BOIL_WATER: String
    +HEAT_STOVE: String
    +HEAT_OVEN: String
    +CHECK_PRODUCTS: String
}

class CentralController {
    -devices: List<DeviceProxy>
    -checker: Checker
    -schedule: ScheduleInterface
    -receipt: Receipt
    +addDevice(device: ProxyDevice)
    +getDevices()
    +checkDevices()
    +executeSchedule()
    +sendAlert()
    +getAllActionLogs()
}

interface Checker {
    +checkAvailability()
    +reportStatus()
}

class CoffeeMachine {
    -type: String
    -isOn: boolean
    -int: waterLevel
    -int: coffeeLevel
    +getStatus()
    +getType()
    +turnOn()
    +turnOff()
    +makeCoffee()
}

interface Device {
    +getStatus()
    +turnOn()
    +turnOff()
    +getType()
    +makeCoffee()
    +boilWater()
    +heatStove(int temperature)
    +heatOven(int temperature, int minutes)
    +checkProducts()
}

class DeviceChecker {
    -controller: CentralController
    +setController(CentralController controller)
    +checkAvailability()
    +reportStatus()
    +parseValue()
}

interface DeviceIterator {
    +hasNext()
    +next()
}

class DeviceListIterator {
    -devices: List<ProxyDevice>
    -currentIndex: int
    +hasNext()
    +next()
}

class Fridge {
    -type: String
    -isOn: boolean
    +milk: int
    +eggs: int
    +getStatus()
    +getType()
    +turnOn()
    +turnOff()
    +checkProducts()
}

class Kettle {
    -type: String
    -isOn: boolean
    -waterLevel: int
    +getStatus()
    +getType()
    +turnOn()
    +turnOff()
    +boilWater()
}

class LoggingDecorator {
    -log: List<String>
    -device: Device
    +getLog()
    +getStatus()
    +getType()
    +turnOn()
    +turnOff()
    +makeCoffee()
    +boilWater()
    +heatOven()
    +heatStove()
    +checkProducts()
}

class ModernCoffeeMachine {
    -type: String
    -isOn: boolean
    -int: waterLevel
    -int: coffeeLevel
    +getModernStatus()
    +getModernType()
    +turnModernOn()
    +turnModernOff()
    +makeModernCoffee()
}

class ModernCoffeeMachineAdapter {
    +getStatus()
    +getType()
    +turnOn()
    +turnOff()
    +makeCoffee()
}

class Oven {
    -type: String
    -isOn: boolean
    -currentTemperature: int
    -remainingMinutes: int
    +getStatus()
    +getType()
    +turnOn()
    +turnOff()
    +heatOven(int temperature, int minutes)
}

class ProxyDevice {
    -realDevice: Device
    -cachedStatus: String
    +getStatus()
    +getType()
    +getLoggingDecorator()
    +turnOn()
    +turnOff()
    +makeCoffee()
    +boilWater()
    +heatStove(int temperature)
    +heatOven(int temperature, int minutes)
    +checkProducts()
}

class Receipt {
    -devices: Map<String, ProxyDevice>
    +addDevice(device: ProxyDevice)
    +makeCoffee()
    +boilWater()
    +heatStove(int temperature)
    +heatOven(int temperature, int minutes)
    +checkProducts()
}

interface ScheduleInterface {
    +setSchedule()
    +getSchedule()
    +setRoutine()
    +getRoutines()
}

class ScheduleManager {
    -tasks: List<Task>
    +setSchedule()
    +getSchedule()
    +setRoutine()
    +getRoutines()
}

class SingleAction {
    -task: Task
    +execute(Receipt receipt)
}

class Stove {
    -type: String
    -isOn: boolean
    -currentTemperature: int
    +getStatus()
    +getType()
    +turnOn()
    +turnOff()
    +heatStove(int temperature)
}

class Task {
    -time: String
    -action: String
    -temperature: int
    -minutes: int
    +getTime()
    +getAction()
    +execute(receipt: Receipt)
}

Device <|.. Stove
Device <|.. Oven
Device <|.. Fridge
Device <|.. Kettle
Device <|.. CoffeeMachine
Device <|.. ModernCoffeeMachineAdapter
Device <|.. LoggingDecorator
Device <|.. ProxyDevice

ModernCoffeeMachine o--> ModernCoffeeMachineAdapter
ProxyDevice o--> Device
LoggingDecorator o--> Device

Receipt o--> ProxyDevice
CentralController o--> ProxyDevice
CentralController o--> ScheduleManager
CentralController o--> Receipt

ScheduleInterface <|.. ScheduleManager
ScheduleManager o--> Task
ScheduleManager o--> ActionComposite

Checker <|.. DeviceChecker
DeviceChecker o--> CentralController

DeviceIterator <|.. DeviceListIterator
DeviceListIterator o--> ProxyDevice
CentralController o--> DeviceIterator

ActionComponent <|.. ActionComposite
ActionComponent <|.. SingleAction
ActionComposite o--> ActionComponent
SingleAction o--> Task
CentralController ..> LoggingDecorator

@enduml