@startuml
interface Device {
    +getStatus()
    +turnOn()
    +turnOff()
    +getDeviceType()
    +makeCoffee()
    +boilWater()
    +heatStove(int temperature)
    +heatOven(int temperature, int minutes)
    +checkProducts()
}

class Stove {
    -isOn: boolean
    -currentTemperature: int
    +getStatus()
    +turnOn()
    +turnOff()
    +heatStove(int temperature)
}

class Oven {
    -isOn: boolean
    -currentTemperature: int
    -remainingMinutes: int
    +getStatus()
    +turnOn()
    +turnOff()
    +heatOven(int temperature, int minutes)
}

class Fridge {
    -isOn: boolean
    +milk: int
    +eggs: int
    +getStatus()
    +turnOn()
    +turnOff()
    +checkProducts()
}

class Kettle {
    -isOn: boolean
    -waterLevel: int
    +getStatus()
    +turnOn()
    +turnOff()
    +boilWater()
}

class CoffeeMachine {
    -isOn: boolean
    -int: waterLevel
    -int: coffeeLevel
    +getStatus()
    +turnOn()
    +turnOff()
    +makeCoffee()
}

class ProxyDevice {
    -realDevice: Device
    -cachedStatus: String
    +ProxyDevice()
    +initializeDevice()
    +getStatus()
    +turnOn()
    +turnOff()
    +makeCoffee()
    +boilWater()
    +heatStove(int temperature)
    +heatOven(int temperature, int minutes)
    +checkProducts()
    +getDeviceType()
}

interface Checker {
    +checkAvailability()
    +reportStatus()
}

class DeviceChecker {
    -controller: CentralController
    +checkAvailability()
    +reportStatus()
    +parseValue()
    +setController(controller: CentralController)
}

interface ScheduleInterface {
    +setSchedule()
    +getSchedule()
}

class ScheduleManager {
    -tasks: List<Task>
    +setSchedule()
    +getSchedule()
}

class CentralController {
    -devices: List<DeviceProxy>
    -checker: Checker
    -schedule: ScheduleInterface
    -receipt: Receipt
    +addDevice(device: ProxyDevice)
    +getDevices()
    +checkDevices()
    +setSchedule()
    +executeSchedule()
    +sendAlert()
}

class Task {
    -time: String
    -action: String
    -temperature: int
    -minutes: int
    +getTime()
    +getAction()
    +execute(receipt: Receipt)
}

class Receipt {
    -devices: Map<String, ProxyDevice>
    +addDevice(device: ProxyDevice)
    +makeCoffee()
    +boilWater()
    +heatStove(int temperature)
    +heatOven(int temperature, int minutes)
    +checkProducts()
}

class ActionConstants{
    +MAKE_COFFEE: String
    +BOIL_WATER: String
    +HEAT_STOVE: String
    +HEAT_OVEN: String
    +CHECK_PRODUCTS: String
}
Device <|.. Stove
Device <|.. Oven
Device <|.. Fridge
Device <|.. Kettle
Device <|.. CoffeeMachine
Device <|.. ProxyDevice
Checker <|.. DeviceChecker
ScheduleInterface <|.. ScheduleManager
CentralController o--> "many" ProxyDevice
CentralController o--> DeviceChecker
CentralController o--> ScheduleManager
CentralController o--> Receipt
ScheduleManager o--> "many" Task

@enduml